import type { ComponentConfig, ThemeConfig } from '@/types'

export const componentConfigs: Record<string, ComponentConfig> = {
  'layout-container': {
    type: 'layout-container',
    label: '容器',
    icon: 'LayoutGrid',
    category: 'layout',
    defaultProps: {
      padding: '16px',
      background: '#ffffff',
      borderRadius: '8px',
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['root', 'layout-container', 'form-container', 'modal'],
    allowedChildren: ['*'],
    propConfig: [
      { key: 'padding', label: '内边距', type: 'text', group: '布局' },
      { key: 'background', label: '背景色', type: 'color', group: '样式' },
      { key: 'borderRadius', label: '圆角', type: 'text', group: '样式' },
      { key: 'border', label: '边框', type: 'text', group: '样式' },
      { key: 'shadow', label: '阴影', type: 'select', group: '样式', options: [
        { label: '无', value: 'none' },
        { label: '小', value: '0 1px 3px rgba(0,0,0,0.1)' },
        { label: '中', value: '0 4px 6px rgba(0,0,0,0.1)' },
        { label: '大', value: '0 10px 15px rgba(0,0,0,0.1)' },
      ]},
    ],
  },
  'layout-row': {
    type: 'layout-row',
    label: '行布局',
    icon: 'Rows3',
    category: 'layout',
    defaultProps: {
      gap: '16px',
      align: 'stretch',
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['root', 'layout-container', 'form-container'],
    allowedChildren: ['layout-col'],
    propConfig: [
      { key: 'gap', label: '间距', type: 'text', group: '布局' },
      { key: 'align', label: '对齐方式', type: 'select', group: '布局', options: [
        { label: '拉伸', value: 'stretch' },
        { label: '顶部', value: 'flex-start' },
        { label: '居中', value: 'center' },
        { label: '底部', value: 'flex-end' },
      ]},
    ],
  },
  'layout-col': {
    type: 'layout-col',
    label: '列布局',
    icon: 'Columns3',
    category: 'layout',
    defaultProps: {
      span: 1,
      minWidth: '0',
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['layout-row'],
    allowedChildren: ['*'],
    propConfig: [
      { key: 'span', label: '占比', type: 'number', group: '布局' },
      { key: 'minWidth', label: '最小宽度', type: 'text', group: '布局' },
    ],
  },
  'basic-button': {
    type: 'basic-button',
    label: '按钮',
    icon: 'MousePointerClick',
    category: 'basic',
    defaultProps: {
      text: '按钮',
      variant: 'primary',
      size: 'medium',
      disabled: false,
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['*'],
    allowedChildren: [],
    propConfig: [
      { key: 'text', label: '文字', type: 'text', group: '基础' },
      { key: 'variant', label: '类型', type: 'select', group: '样式', options: [
        { label: '主要', value: 'primary' },
        { label: '次要', value: 'secondary' },
        { label: '文字', value: 'text' },
        { label: '危险', value: 'danger' },
      ]},
      { key: 'size', label: '尺寸', type: 'select', group: '样式', options: [
        { label: '小', value: 'small' },
        { label: '中', value: 'medium' },
        { label: '大', value: 'large' },
      ]},
      { key: 'disabled', label: '禁用', type: 'boolean', group: '状态' },
    ],
  },
  'basic-input': {
    type: 'basic-input',
    label: '输入框',
    icon: 'Type',
    category: 'basic',
    defaultProps: {
      placeholder: '请输入',
      label: '标题',
      value: '',
      showLabel: true,
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['form-container', 'form-item', 'layout-container', 'root'],
    allowedChildren: [],
    propConfig: [
      { key: 'label', label: '标签', type: 'text', group: '基础' },
      { key: 'showLabel', label: '显示标签', type: 'boolean', group: '基础' },
      { key: 'placeholder', label: '占位文字', type: 'text', group: '基础' },
      { key: 'value', label: '默认值', type: 'text', group: '数据' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: '状态' },
    ],
  },
  'basic-select': {
    type: 'basic-select',
    label: '下拉选择',
    icon: 'ChevronDown',
    category: 'basic',
    defaultProps: {
      label: '选择',
      placeholder: '请选择',
      showLabel: true,
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['form-container', 'form-item', 'layout-container', 'root'],
    allowedChildren: [],
    propConfig: [
      { key: 'label', label: '标签', type: 'text', group: '基础' },
      { key: 'showLabel', label: '显示标签', type: 'boolean', group: '基础' },
      { key: 'placeholder', label: '占位文字', type: 'text', group: '基础' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: '状态' },
    ],
  },
  'basic-text': {
    type: 'basic-text',
    label: '文本',
    icon: 'Text',
    category: 'basic',
    defaultProps: {
      content: '这是一段文本内容',
      fontSize: '14px',
      color: '#333333',
      fontWeight: 'normal',
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['*'],
    allowedChildren: [],
    propConfig: [
      { key: 'content', label: '内容', type: 'textarea', group: '基础' },
      { key: 'fontSize', label: '字号', type: 'text', group: '样式' },
      { key: 'color', label: '颜色', type: 'color', group: '样式' },
      { key: 'fontWeight', label: '字重', type: 'select', group: '样式', options: [
        { label: '细', value: '300' },
        { label: '正常', value: 'normal' },
        { label: '中等', value: '500' },
        { label: '粗', value: 'bold' },
      ]},
    ],
  },
  'form-container': {
    type: 'form-container',
    label: '表单容器',
    icon: 'FileText',
    category: 'form',
    defaultProps: {
      layout: 'vertical',
      labelWidth: '100px',
      labelPosition: 'right',
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['root', 'layout-container', 'modal'],
    allowedChildren: ['form-item', 'basic-input', 'basic-select', 'basic-button'],
    propConfig: [
      { key: 'layout', label: '布局', type: 'select', group: '布局', options: [
        { label: '垂直', value: 'vertical' },
        { label: '水平', value: 'horizontal' },
        { label: '行内', value: 'inline' },
      ]},
      { key: 'labelWidth', label: '标签宽度', type: 'text', group: '布局' },
      { key: 'labelPosition', label: '标签位置', type: 'select', group: '布局', options: [
        { label: '左', value: 'left' },
        { label: '右', value: 'right' },
        { label: '上', value: 'top' },
      ]},
    ],
  },
  'form-item': {
    type: 'form-item',
    label: '表单项',
    icon: 'List',
    category: 'form',
    defaultProps: {
      label: '表单项',
      required: false,
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['form-container'],
    allowedChildren: ['basic-input', 'basic-select', 'basic-button'],
    propConfig: [
      { key: 'label', label: '标签', type: 'text', group: '基础' },
      { key: 'required', label: '必填', type: 'boolean', group: '校验' },
    ],
  },
  'display-table': {
    type: 'display-table',
    label: '表格',
    icon: 'Table',
    category: 'display',
    defaultProps: {
      columns: 3,
      rows: 4,
      bordered: true,
      striped: true,
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['root', 'layout-container', 'form-container'],
    allowedChildren: [],
    propConfig: [
      { key: 'columns', label: '列数', type: 'number', group: '基础' },
      { key: 'rows', label: '行数', type: 'number', group: '基础' },
      { key: 'bordered', label: '边框', type: 'boolean', group: '样式' },
      { key: 'striped', label: '斑马纹', type: 'boolean', group: '样式' },
    ],
  },
  'display-card': {
    type: 'display-card',
    label: '卡片',
    icon: 'Square',
    category: 'display',
    defaultProps: {
      title: '卡片标题',
      showHeader: true,
      shadow: 'medium',
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['*'],
    allowedChildren: ['*'],
    propConfig: [
      { key: 'title', label: '标题', type: 'text', group: '基础' },
      { key: 'showHeader', label: '显示头部', type: 'boolean', group: '基础' },
      { key: 'shadow', label: '阴影', type: 'select', group: '样式', options: [
        { label: '无', value: 'none' },
        { label: '小', value: 'small' },
        { label: '中', value: 'medium' },
        { label: '大', value: 'large' },
      ]},
    ],
  },
  'feedback-modal': {
    type: 'feedback-modal',
    label: '弹窗',
    icon: 'RectangleVertical',
    category: 'feedback',
    defaultProps: {
      title: '弹窗标题',
      width: '520px',
      visible: true,
      showFooter: true,
    },
    defaultStyles: {},
    canHaveChildren: true,
    allowedParents: ['root'],
    allowedChildren: ['*'],
    propConfig: [
      { key: 'title', label: '标题', type: 'text', group: '基础' },
      { key: 'width', label: '宽度', type: 'text', group: '尺寸' },
      { key: 'visible', label: '显示', type: 'boolean', group: '状态' },
      { key: 'showFooter', label: '显示底部', type: 'boolean', group: '基础' },
    ],
  },
  'basic-image': {
    type: 'basic-image',
    label: '图片',
    icon: 'Image',
    category: 'basic',
    defaultProps: {
      src: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=abstract%20gradient%20purple%20blue%20soft%20background&image_size=square',
      alt: '图片',
      width: '100%',
      borderRadius: '8px',
      fit: 'cover',
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['*'],
    allowedChildren: [],
    propConfig: [
      { key: 'src', label: '图片地址', type: 'text', group: '基础' },
      { key: 'alt', label: '替代文字', type: 'text', group: '基础' },
      { key: 'width', label: '宽度', type: 'text', group: '尺寸' },
      { key: 'borderRadius', label: '圆角', type: 'text', group: '样式' },
      { key: 'fit', label: '填充方式', type: 'select', group: '样式', options: [
        { label: '覆盖', value: 'cover' },
        { label: '包含', value: 'contain' },
        { label: '填充', value: 'fill' },
        { label: '原始', value: 'none' },
      ]},
    ],
  },
  'basic-divider': {
    type: 'basic-divider',
    label: '分割线',
    icon: 'Minus',
    category: 'basic',
    defaultProps: {
      orientation: 'horizontal',
      color: '#e5e7eb',
      thickness: '1px',
    },
    defaultStyles: {},
    canHaveChildren: false,
    allowedParents: ['*'],
    allowedChildren: [],
    propConfig: [
      { key: 'orientation', label: '方向', type: 'select', group: '基础', options: [
        { label: '水平', value: 'horizontal' },
        { label: '垂直', value: 'vertical' },
      ]},
      { key: 'color', label: '颜色', type: 'color', group: '样式' },
      { key: 'thickness', label: '粗细', type: 'text', group: '样式' },
    ],
  },
}

export const categoryList = [
  { key: 'basic', label: '基础组件' },
  { key: 'layout', label: '布局容器' },
  { key: 'form', label: '表单组件' },
  { key: 'display', label: '展示组件' },
  { key: 'feedback', label: '反馈组件' },
]

export const themes: ThemeConfig[] = [
  {
    id: 'default',
    name: '默认主题',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    borderColor: '#e5e7eb',
  },
  {
    id: 'dark',
    name: '暗黑主题',
    primaryColor: '#818cf8',
    secondaryColor: '#a78bfa',
    backgroundColor: '#1f2937',
    textColor: '#f9fafb',
    borderColor: '#374151',
  },
  {
    id: 'ocean',
    name: '海洋主题',
    primaryColor: '#0ea5e9',
    secondaryColor: '#06b6d4',
    backgroundColor: '#ffffff',
    textColor: '#1e293b',
    borderColor: '#e2e8f0',
  },
  {
    id: 'forest',
    name: '森林主题',
    primaryColor: '#10b981',
    secondaryColor: '#14b8a6',
    backgroundColor: '#ffffff',
    textColor: '#065f46',
    borderColor: '#d1fae5',
  },
]
